name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: configure DNS server
        run: |
          sudo mkdir /usr/lib/systemd/resolved.conf.d
          echo "[Resolve]" > resolved.conf
          echo "DNS=8.8.8.8" >> resolved.conf
          sudo mv resolved.conf /usr/lib/systemd/resolved.conf.d/resolved.conf
          sudo systemctl daemon-reload
          sudo systemctl restart systemd-networkd
          sudo systemctl restart systemd-resolved
      - name: install and lint
        working-directory: ./scripts
        run: |
          npm install
          npm run lint
      - name: update papers
        working-directory: ./scripts
        run: |
          rm ../data/**/_Example.ttl
          npm run papers
      - name: build
        working-directory: ./scripts
        run: npm run build
      - name: prepare deploy
        working-directory: ./scripts
        run: |
          cp exoframe.json public/
          cp Dockerfile public/
      - name: deploy
        working-directory: ./scripts/public
        run: npx exoframe -u -vvv -e https://dice-website.cs.upb.de -t $EXO_TOKEN_DICE
        env:
          EXO_TOKEN_DICE: ${{ secrets.EXO_TOKEN_DICE }}
  syncBranches:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: merge master to develop
        run: |
          git config --global user.email "bot@dice-research.org"
          git config --global user.name "DICE Bot"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git checkout develop
          git merge origin/master
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
