# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: mkdir /usr/lib/systemd/resolved.conf.d
    - run: echo "[Resolve]" >> /usr/lib/systemd/resolved.conf.d/resolved.conf
    - run: echo "DNS=8.8.8.8" >> /usr/lib/systemd/resolved.conf.d/resolved.conf
    - run: systemctl daemon-reload
    - run: systemctl restart systemd-networkd
    - run: systemctl restart systemd-resolved
    - run: nslookup dice-website.cs.upb.de
